# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='block_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
