# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-06 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20160506_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='txoutput',
            name='script_pk_string',
            field=models.CharField(default='', max_length=100),
        ),
    ]
