# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_txoutput_script_pk_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txoutput',
            name='script_pk_string',
            field=models.CharField(default='', max_length=500),
        ),
    ]
