# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20160507_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='tx',
            name='tx_hash',
            field=models.CharField(default='', max_length=100),
        ),
    ]
